[package]
name = "mdblocks"
version = "0.1.0"
authors = ["John Morris <johnmorris@tuta.io>"]
edition = "2018"
description = "Extract the contents of code blocks in markdown"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
